services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: always
        environment:
            DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}?sslmode=require
            ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
            SENDER_EMAIL: ${SENDER_EMAIL}
            SENDER_PASSWORD: ${SENDER_PASSWORD}

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - backend
        ports:
            - "3000:3000"
