"""Added sorting index for experience and role

Revision ID: 8ffe64b18708
Revises: bc916d1a69e4
Create Date: 2026-03-26 17:52:18.435951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffe64b18708'
down_revision: Union[str, Sequence[str], None] = 'bc916d1a69e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('role', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'sort_order')
    op.drop_column('experience', 'sort_order')
    # ### end Alembic commands ###
