"""Added experience and role tables

Revision ID: bc916d1a69e4
Revises: 20f56b4a8b7a
Create Date: 2026-03-26 13:13:06.858247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc916d1a69e4'
down_revision: Union[str, Sequence[str], None] = '20f56b4a8b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
    sa.Column('experience_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('experience_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('date_range', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experience.experience_id'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_table('experience')
    # ### end Alembic commands ###
